#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace WeBee\gCMS;

$possibleFiles = [
    __DIR__.'/../../autoload.php',
    __DIR__.'/../autoload.php',
    __DIR__.'/vendor/autoload.php',
];
$file = null;

foreach ($possibleFiles as $possibleFile) {
    if (file_exists($possibleFile)) {
        $file = $possibleFile;
        break;
    }
}

if (null === $file) {
    throw new \RuntimeException('Unable to locate autoload.php file.');
}

require_once $file;

unset($possibleFiles, $possibleFile, $file);

use Symfony\Component\Console\Application;
use WeBee\gCMS\Command\GenerateCommand;

$app = new Application();

$app->add(
    new GenerateCommand()
);

$app->run();

__halt_compiler();
