#!/usr/bin/env php
<?php

/**
 * This file is part of the gCMS package. For full copyright and licence information,
 * please view the LICENCE file that was distributed with this source code.
 *
 * (c) Adam Wojciechowski <adam@webee.online>
 */

declare(strict_types=1);

namespace WeBee\gCMS;

$possibleFiles = [
    __DIR__.'/../../autoload.php',
    __DIR__.'/../autoload.php',
    __DIR__.'/vendor/autoload.php',
];
$file = null;

foreach ($possibleFiles as $possibleFile) {
    if (file_exists($possibleFile)) {
        $file = $possibleFile;
        break;
    }
}

if (null === $file) {
    throw new \RuntimeException('Unable to locate autoload.php file.');
}

require_once $file;

unset($possibleFiles, $possibleFile, $file);

use Symfony\Component\Console\Application;
use WeBee\gCMS\Command\BuildCommand;
use WeBee\gCMS\Command\UpdateCommand;

$app = new Application('gCMS Manager', '1.0');

$app->add(new BuildCommand());
$app->add(new UpdateCommand());

$app->run();

__halt_compiler();
